### ISSUE TITLE
Failed to generate podspec for pods with subspec

### ISSUE THREAD

**Issue by ainopara** [X140Yu/cocoapods-show-podpsecs-in-project#3]
### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/ainopara/Documents/Projects/Stage1st-Reader/Pods/Podspecs/YapDatabase/Standard.podpsec.json
/Library/Ruby/Gems/2.3.0/gems/cocoapods-show-podpsecs-in-project-0.1.1/lib/cocoapods_plugin.rb:13:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-show-podpsecs-in-project-0.1.1/lib/cocoapods_plugin.rb:13:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-show-podpsecs-in-project-0.1.1/lib/cocoapods_plugin.rb:13:in `block (2 levels) in <module:CocoapodsGitHooks>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-show-podpsecs-in-project-0.1.1/lib/cocoapods_plugin.rb:10:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-show-podpsecs-in-project-0.1.1/lib/cocoapods_plugin.rb:10:in `block in <module:CocoapodsGitHooks>'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:101:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/hooks_manager.rb:100:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:455:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:433:in `perform_post_install_actions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:125:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```
Ref:
https://github.com/yapstudios/YapDatabase/blob/a88e92d972cb454b5ba53f7ce04a33f49246bea8/YapDatabase.podspec#L31

We should skip a spec if it is a subspec since it's name will resolved to be `spec_name/subspec_name`.

**Comment by X140Yu** [comment]
Thanks for reporting!

This bug has been fixed and the new version is delivered, try `gem install cocoapods-show-podpsecs-in-project` to install version `0.1.2`.
